<?php defined('BASEPATH') OR exit('No direct script access allowed');

$form = new zea();
$form->init('roll');
$form->setTable('prala_pendidikan');
$form->search();
$form->join('prala','ON(prala.id=prala_pendidikan.prala_id)','prala.id,prala.no_registration AS reg_id,prala.nama,prala.kode_pelaut,prala_pendidikan.prodi_id,prala.nama_sekolah');
$delimeter = !empty($_GET['keyword']) ? 'AND' : '';
$form->setWhere(" {$delimeter} prala_pendidikan.prodi_id != '' group by prala.id");
$form->setNumbering(TRUE);
$form->addInput('id','hidden');
$form->addInput('kode_pelaut','plaintext');
$form->setLabel('kode_pelaut',' Kode Pelaut');
$form->addInput('nama','link');
$form->setLink('nama', base_url('admin/prala/pendidikan/detail'),'reg_id');
$form->addInput('nama_sekolah','plaintext');
$form->setLabel('nama_sekolah','Asal Sekolah');
// $form->setExtLink('nama','&id=');
$form->addInput('prodi_id','dropdown');
$form->tableOptions('prodi_id','prodi','id','title');
$form->setAttribute('prodi_id','disabled');
$form->setLabel('prodi_id','Program Studi');
$form->form();
// pr($form->getData());